apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  labels:
    app: db
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS userdb;
    USE userdb;
    CREATE TABLE users(user_id INT PRIMARY KEY AUTO_INCREMENT, user_name VARCHAR(255), user_email VARCHAR(255), user_password VARCHAR(255));